In [1]:
%matplotlib inline

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
from sklearn.model_selection import train_test_split

x = pd.read_csv('./Data/Intermediate_results/X.csv')
y = x['worldwide_gross']
x = x.drop('worldwide_gross', axis = 1)
x = x.drop('gross', axis = 1)

x_train, x_test, y_train, y_test = train_test_split(x,y)

In [6]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(x_train, y_train)

StandardScaler()

In [7]:
scaler.mean_

array([3.40300051e+07, 2.00192711e+03, 2.12420856e+00, 1.08547377e+02,
       1.03424670e+04, 3.77247143e+07, 6.45428571e+00])

In [8]:
#standar desviation for each feature
scaler.scale_

array([4.24499774e+07, 1.22373628e+01, 7.23892971e-01, 2.28994603e+01,
       1.96787234e+04, 6.74852924e+07, 1.08010165e+00])

In [9]:
#centralization
scaler.transform(x_train)

array([[-0.09493539,  0.90484276,  0.31191274, ..., -0.23560812,
        -0.11446515, -0.79093085],
       [ 0.84735015,  0.00595628,  0.31191274, ...,  0.28322635,
         0.33007615, -0.1428437 ],
       [ 1.08292154,  0.25110714, -0.37879711, ..., -0.43389334,
         0.55234681, -0.1428437 ],
       ...,
       [ 0.25842169, -0.64777934,  0.31191274, ...,  0.09241113,
         0.1078055 , -0.1428437 ],
       [-0.54252102, -2.20040145, -0.64126685, ..., -0.46946475,
        -0.39600798,  1.52366612],
       [-0.68386385,  1.14999362,  0.31191274, ..., -0.40309866,
        -0.00891043,  0.59782733]])

In [11]:
x_train_scaled, x_test_scaled = (scaler.transform(x_train),scaler.transform(x_test) )

In [12]:
from sklearn.linear_model import Lasso

model = Lasso()
model_scaled = Lasso()

model.fit(x_train, y_train)
model_scaled.fit(x_train_scaled, y_train)

Lasso()

In [14]:
print(model.score(x_test, y_test))
print(model_scaled.score(x_test_scaled, y_test))

0.517527365968544
0.51752736704885


In [16]:
#scaling data without scaling each data split
from sklearn.pipeline import make_pipeline

model_scaled = make_pipeline(StandardScaler(), Lasso())

model_scaled.fit(x_train, y_train)

Pipeline(steps=[('standardscaler', StandardScaler()), ('lasso', Lasso())])

In [17]:
print(model_scaled.score(x_test, y_test))

0.51752736704885


Creating new features automatically

In [18]:
A = np.arange(6).reshape(3,2)
A

array([[0, 1],
       [2, 3],
       [4, 5]])

In [21]:
from sklearn.preprocessing import PolynomialFeatures

transformer = PolynomialFeatures(2)
transformer.fit_transform(A)


array([[ 1.,  0.,  1.,  0.,  0.,  1.],
       [ 1.,  2.,  3.,  4.,  6.,  9.],
       [ 1.,  4.,  5., 16., 20., 25.]])

In [22]:
x.shape

(4061, 7)

In [24]:
transformer = PolynomialFeatures(2)
transformer.fit_transform(x).shape

(4061, 36)

In [25]:
model_poly = make_pipeline(PolynomialFeatures(2), Lasso())

model_poly.fit(x_train, y_train)

d:\CURSOS\14. ML aplicado Python\venv\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:530: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 1.657976795805674e+19, tolerance: 9724260611340594.0
  model = cd_fast.enet_coordinate_descent(


Pipeline(steps=[('polynomialfeatures', PolynomialFeatures()),
                ('lasso', Lasso())])

In [26]:
model_poly.score(x_test, y_test)

0.5451109929901353